### ISSUE TITLE
Getting resets

### ISSUE THREAD

**Issue by mizzunet** [davidjameshowell/bitwarden_rs_heroku#3]
I have deployed this on Heroku. Signed up and logged in. But the thing is it just sign outs itselft after some time and asking for logging in. But it says wrong password.
So I created another account with account with same email(I shouldn't be able to create with the same, unless there's no account, means it gets resets). And the sign out happens again. It's getting reset I guess. 

I'm not sure what kind of logs can I provide you.
Here's the link anyway: https://bwarden.herokuapp.com
BTW, you've telegram account?

**Comment by davidjameshowell** [comment]
Can you check your github workflow and set duo enable to 0.

My Telegram is nowai_david - we can chat and then provide an update on here afterwards on what the root cause was.

**Comment by davidjameshowell** [comment]
I was monitoring an testing out on your instance and can confirm - it actually looks like something is wiping out your database instance possibly as creating another account and logging in does not return the test item I had.

Can you reach out on Telegram for further troubleshooting?
