### ISSUE TITLE
Can you add an automatic backup function?

### ISSUE THREAD

**Issue by ymcoming** [davidjameshowell/bitwarden_rs_heroku#7]
For example, backup to Google Drive

**Comment by zhongfly** [comment]
waiting for this too

**Comment by davidjameshowell** [comment]
Definitely can consider something like this - let me think of some easy to use ways for all.

Would just a SQL dump of the database do?

**Comment by ymcoming** [comment]
Yes, I need to export the SQL database function.
thx!

**Comment by davidjameshowell** [comment]
Planned functionality is to use Autobus to do database backups. Unfortunately this does mean it will be relegated to Heroku verified accounts as it is another Dyno. Otherwise you can take backup via MySQL workbench/mysql dump.

**Comment by davidjameshowell** [comment]
#12 should help with this. For non-verified accounts, I would suggest using mysql dump to take a copy as automation without it is more difficult.
